volumes:
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  cookease:
    build:
      context: cookease
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./cookease:/app
    environment:
      SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY}
      DATABASE_URL: mongodb://root:password@localhost:27017/?authMechanism=DEFAULT
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_NAME: db-name
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_COOKEASE_API_HOST: http://localhost:8000
      REACT_APP_SPOONACULAR_HOST: https://api.spoonacular.com/recipes/complexSearch?

# changed line 43 from REACT_API_COOKEASE_API_HOST
