# fly.toml app configuration file generated for cookease on 2024-06-06T19:16:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cookease'
primary_region = 'iad'

[build]

[env]
  database_url = "mongodb://root:password@mongo/admin"
  DATABASE_NAME = 'db-name'
  WAIT_HOSTS = 'mongo:27017'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
